no_display

legacy_layout=0

table_columns=4

fps_text=FPS
fps
fps_metrics=avg,0.01

gpu_text=9070 XT
gpu_list=0
gpu_stats
gpu_temp
gpu_power

vram

cpu_text=9800X3D
cpu_stats
cpu_temp
cpu_mhz

ram

font_size=20

background_color=191724
background_alpha=0.5

text_color=e0def4

engine_color=eb6f92
gpu_color=31748f
vram_color=9ccfd8
cpu_color=c4a7e7
ram_color=ebbcba
