profile=high-quality

keep-open=yes
save-position-on-quit

screenshot-format=png
screenshot-dir="~/pictures/screenshots"
screenshot-template="%F-%p-%n"
screenshot-high-bit-depth=no

osd-bar=no
border=no
cursor-autohide=100

sub-ass-override=no
sub-ass-style-overrides=playresx=2560,playresy=1440
sub-font="Gandhi Sans"
sub-font-size=50
sub-color="#FFFFFF"
sub-margin-y=40
sub-border-size=2.4
sub-border-color="#FF000000"
sub-shadow-color="#A0000000"
sub-shadow-offset=0.75
sub-bold=yes
sub-ass-style-overrides=Kerning=yes
