[theme]
builtin = "Rosé Pine"

[bar.default]
position = "bottom"
background_opacity = 0.85
margins_end = 100
thickness = 30
start = [ "launcher", "wallpaper", "workspaces" ]
center = [ "clock" ]
end = [ "tray", "session"]

[wallpaper]
directory = "~/pictures/wallpapers"
fill_color = "#191727"

[noctalia_state]
setup_wizard_completed = true

[shell]
settings_show_advanced = true
polkit_agent = true
font_family = "Inter"
