[ no-osd add speed -0.1; script-binding uosc/flash-speed
] no-osd add speed +0.1; script-binding uosc/flash-speed
\ no-osd set speed 1;    script-binding uosc/flash-speed

left no-osd seek -5;
left no-osd seek -5;

ctrl+right no-osd seek  15; script-binding uosc/flash-timeline
ctrl+left  no-osd seek -15; script-binding uosc/flash-timeline

ctrl+shift+right no-osd seek 85; script-binding uosc/flash-timeline
Ctrl+Shift+left no-osd seek -85; script-binding uosc/flash-timeline

up no-osd add volume 10;    script-binding uosc/flash-volume
down no-osd add volume -10; script-binding uosc/flash-volume
m no-osd cycle mute;        script-binding uosc/flash-volume

k cycle_values sub-ass-override "force" "no"

ctrl+o script-binding uosc/open-file

CTRL+` no-osd change-list glsl-shaders clr ""; show-text "GLSL shaders cleared"
CTRL+1 no-osd change-list glsl-shaders set "~~/shaders/FSR.glsl"; show-text "FSR"
CTRL+2 no-osd change-list glsl-shaders set "~~/shaders/ArtCNN_C4F32.glsl"; show-text "ArtCNN"
CTRL+3 no-osd change-list glsl-shaders set "~~/shaders/nnedi3-nns128-win8x4.hook"; show-text "nnedi3"
