theme {
  color_scheme = $HOME/.config/hypr/misc/qt_theme.conf
  icon_theme = breeze-dark
  style = Fusion
  font = Noto Sans
  font_size = 11
  font_fixed = JetBrains Mono
  font_fixed_size = 11
}

misc {
  single_click_activate = true
  menus_have_icons = false
  shortcuts_for_context_menus = false
}
